routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware('guest')->group( function() {

    Route::get('/{any}', fn() => view('index'))->where(['any' => 'login|forgot-password|register']);

    Route::post('/login', [ LoginController::class, 'authenticate' ])->name('login');

    Route::post('/forgot-password', [ ResetPasswordController::class, 'sendEmailForm' ])->name('password.email');

    Route::get('/reset-password/{token}', fn() => view('index'))->name('password.reset');

    Route::post('/reset-password', [ ResetPasswordController::class, 'resetPassword' ]);

    Route::post('/register', [ RegisterController::class, 'register' ]);

});

Route::middleware('auth')->group(function() {
    Route::get('/email/verify', fn() => view('index'))->name('verification.notice');

    Route::middleware('signed')
        ->get('/email/verify/{id}/{hash}', [ LoginController::class, 'verifyEmail' ])
        ->name('verification.verify');

    Route::middleware('throttle:6,1')
        ->post('/email/verification-notification', [ LoginController::class, 'resendVerificationEmail' ])
        ->name('verification.send');

    Route::post('/logout', [ LoginController::class, 'deauthenticate' ])->name('logout');
});

Route::fallback(fn() => view('index'))->middleware([ 'verified', 'auth:sanctum' ]);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\HasRole;
use App\Traits\Filterable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable, HasRole, SoftDeletes, Filterable;

    const FEMALE_GENDER = 'F';
    const MALE_GENDER = 'M';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'identification_card',
        'name',
        'last_name',
        'username',
        'email',
        'password',
        'phone',
        'birthdate',
        'gender'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function patients()
    {
        return $this->belongsToMany(Patient::class)->withPivot('relationship');
    }

    public function specialities()
    {
        return $this->belongsToMany(Speciality::class);
    }

    public function exams()
    {
        return $this->hasMany(Exam::class, 'technician_id');
    }

    public function address()
    {
        return $this->belongsTo(Address::class);
    }

    public function getFullNameAttribute()
    {
        return "$this->name $this->last_name";
    }

    public function getRelationshipAttribute()
    {
        return $this->pivot->relationship;
    }
}

resources/views/exports/pdf/prescription.blade.php
<style>
    h5 {
        font-size: 1.25rem;
    }
    .prescriptions, .info {
        width: 100%;
    }
    .prescriptions .drug {
        width: 25%;
    }
    .prescriptions .medication {
        width: 75%;
    }
</style>
<h5>Receta médica</h5>
<table class="info">
    <tbody>
        <tr>
            <td>
                <span class="d-block"><strong>Paciente: </strong>{{ $patient->full_name }}</span>
            </td>
            <td>
                <span class="d-block"><strong>Genero: </strong>{{ $patient->gender === 'M' ? 'Masculino' : 'Femenino'  }}</span>
            </td>
        </tr>
        <tr>
            <td>
                <span class="d-block"><strong>Doctor: </strong>{{ $doctor->full_name }}</span>
            </td>
            <td>
                <span class="d-block"><strong>Teléfono: </strong>{{ $doctor->phone }}</span>
            </td>
        </tr>
    </tbody>
</table>
<h5>Receta</h5>
<table class="prescriptions">
    <thead>
        <tr>
            <th>Medicamento</th>
            <th>Tratamiento</th>
        </tr>
    </thead>
    <tbody>
        @foreach($prescriptions as $prescription)
            <tr>
                <td class="drug">{{ $prescription->drug }}</td>
                <td class="medication">{{ $prescription->medication }}</td>
            </tr>
        @endforeach
    </tbody>
</table> 
<p>Recuerde seguir el tratamiento como se lo indicó el médico</p>